# Generated by Django 2.1.5 on 2020-04-18 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200418_1258'),
        ('posts', '0002_auto_20200412_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='team',
            field=models.ForeignKey(default='club', on_delete=django.db.models.deletion.CASCADE, to='data.Club'),
        ),
    ]
