# Generated by Django 2.1.5 on 2020-04-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='team',
            field=models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, to='data.Club'),
        ),
    ]
