# Generated by Django 2.1.5 on 2020-04-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200418_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Club'),
        ),
    ]
