# Generated by Django 2.1.5 on 2020-04-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200418_1635'),
        ('posts', '0002_auto_20200418_1739'),
    ]

    operations = [
    ]
