# Generated by Django 3.0.4 on 2020-04-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getamount',
            name='value',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
