# Generated by Django 3.0.4 on 2020-04-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200409_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='getamount',
            name='name',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
