# Generated by Django 3.0.4 on 2020-03-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=120)),
                ('league', models.CharField(max_length=120)),
                ('pic', models.CharField(max_length=120)),
                ('gender', models.CharField(default='male', max_length=120)),
            ],
        ),
    ]
