# Generated by Django 3.0.4 on 2020-03-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200326_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
