# Generated by Django 3.0.4 on 2020-03-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_club_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_scrape',
        ),
        migrations.AlterField(
            model_name='club',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
